name: chainstack
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  # Dependency Injection tool
  get_it: ^8.2.0
  injectable: ^2.5.1
  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  # Freezed - bloc, models gen
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  # Reactive programming tool
  rxdart: ^0.28.0
  # Network
  dio: ^5.9.0
  json_annotation: ^4.9.0
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.5
  http_cache_file_store: ^2.0.1
  url_launcher: ^6.3.2
  dio_cache_interceptor: ^4.0.3
  # UI
  theme_tailor_annotation: ^3.0.2
  provider: ^6.1.5+1
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  oktoast: ^3.4.0
  sliver_tools: ^0.2.12
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0

  # tools
  mask_text_input_formatter: ^2.9.0

  collection: ^1.19.1
  shared_preferences: 2.5.3

  # Navigator
  beamer: ^1.7.0
  flutter_secure_storage: 9.2.4

  easy_localization: ^3.0.8


  # logger
  talker_dio_logger: ^5.0.0
  talker_flutter: ^5.0.0
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.10.0
  injectable_generator: ^2.8.1

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/


  fonts:
    - family: FluentIcons
      fonts:
        - asset: assets/fonts/FluentIcons.ttf
